version: '3'
volumes:
  dados:
networks:
  database:
  web:
  queue:
services:
  db:
    image: postgres:13-alpine
    volumes:
      - dados:/var/lib/postgresql/data
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - database
  frontend:
    image: nginx:1.13
    volumes:
      # Site
      - ./web:/usr/share/nginx/html/
      # nginx reverse proxy config
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - web
    depends_on:
      - app
  app:
    image: python:3.6
    volumes:
      - ./app:/app
    working_dir: /app
    command: bash ./app.sh
    networks:
      - database
      - web
      - queue
    depends_on:
      - db
      - queue_service
  queue_service:
    image: redis:3.2
    networks:
      - queue
  worker:
    #image: python:3.6
    build: worker
    volumes:
      # Worker
      - ./worker:/worker
    working_dir: /worker
    #command: bash ./app.sh
    command: worker.py
    networks:
      - queue
    depends_on:
      - queue_service